const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
    compareDirs: (dir1, dir2) => ipcRenderer.invoke("compare-dirs", dir1, dir2),
    scan_folder: (dir, file_list={}, root) => ipcRenderer.invoke("scan-folder", dir, file_list, root),
    sync_files: (dir1, dir2, DBFile) => ipcRenderer.invoke("sync-files", dir1, dir2, DBFile),
    save_updateTaskInDB: (task) =>ipcRenderer.invoke("save-update-task-db", task),
    removeTaskFromDB: (taskName) =>ipcRenderer.invoke("remove-task-db", taskName),
    get_sync_mode_fromDB: (taskName) =>ipcRenderer.invoke("get-sync-mode-db", taskName),
    get_delete_file_method_fromDB: (taskName) =>ipcRenderer.invoke("get-delete-method-db", taskName),
    get_filter_settings_fromDB: (taskName) =>ipcRenderer.invoke("get-filter-settings-db", taskName),
    get_schedule_settings_fromDB: (taskName) =>ipcRenderer.invoke("get-schedule-settings-db", taskName),
    get_versioning_folder_fromDB: (taskName) =>ipcRenderer.invoke("get-versioning-folder-db", taskName),
    updateTaskDraft: (data) => ipcRenderer.invoke("update-task-draft", data),
    saveTask: () => ipcRenderer.invoke("save-task"),
    openTaskSettings: (taskId) => ipcRenderer.invoke("open-task-settings", taskId),
    startNewTask: () =>  ipcRenderer.invoke("start-new-task"),
    get_task_name_by_id: (taskId) => ipcRenderer.invoke("get_task_name_by_id", taskId),
    get_bd_file_by_id: (taskId) => ipcRenderer.invoke("get_bd_file_by_id", taskId),
    isScheduleEnabled: (taskId) => ipcRenderer.invoke("is-schedule-enabled", taskId),
    toggleSchedule: (enabled, taskId) => ipcRenderer.invoke("toggle-schedule", enabled, taskId),
    getCurrentTaskDraft: () =>  ipcRenderer.invoke("get-current-task-draft"),
    getDefaultTaskDraft: () =>  ipcRenderer.invoke("get-default-task-draft"),
    runTaskNow: (taskId) =>  ipcRenderer.invoke("run-task-now", taskId),
    getTaskList: () =>  ipcRenderer.invoke("get-task-list"),
    update_last_sync : (DBFile, timestamp = Date.now()) => ipcRenderer.invoke("update-last-sync", DBFile, timestamp),
    saveTaskInTaskList: (taskId, taskName, configFilePath) => ipcRenderer.invoke("save-task-in-task-list", taskId, taskName, configFilePath),
    removeConfigFileFromFolder: (DBFile) => ipcRenderer.invoke("remove-config-fileFromFolder", DBFile),
    checkPathExists: (p) => ipcRenderer.invoke("check-path-exists", p),
    deleteTask: (taskId) => ipcRenderer.invoke("delete-task", taskId),
    isThereActiveTask: (taskId) => ipcRenderer.invoke("is-there-active-task"),

    onRefreshDraftUI: (callback) => ipcRenderer.on("refresh-draft-ui", callback),
    onRefreshTaskList: (callback) => ipcRenderer.on("refresh-task-list", callback),
    onResetUI: (callback) => ipcRenderer.on("reset-ui", callback),

    openWindow: (name) => ipcRenderer.send("open-window", name),
    hideWindow: (name) => ipcRenderer.send("hide-window", name),
});